SAVEHIST=5000
HISTSIZE=5000
DIRSTACKSIZE=20

setopt  APPEND_HISTORY
setopt  HIST_IGNORE_ALL_DUPS
setopt  HIST_IGNORE_SPACE
setopt  HIST_REDUCE_BLANKS

setopt  No_Beep
setopt  IGNORE_EOF

setopt  EXTENDED_GLOB
