#!/bin/sh

. .helpers.sh

if [ "${OS}" == 'Mac' ]; then
  BIN="/Applications/Atom.app/Contents/Resources/app/atom.sh"
elif [ "${OS}" == 'Linux' ]; then
  BIN="atom"
else
  echo "Your platform ($(uname -a)) is not supported."
  exit 1
fi

exec /usr/bin/env "${BIN}" $@
